use_frameworks!
platform :ios, '8.0'
target 'Chopper_Example' do
    pod 'Chopper', :path => '../'

  target 'Chopper_Tests' do
    inherit! :search_paths

    pod 'Quick', '1.3.1'
    pod 'Nimble', '7.3.0'
  end
end
